# Generated by Django 3.2.6 on 2021-08-19 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_reader',
        ),
    ]
